# Generated by Django 5.2.5 on 2025-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='סוג מבוקש')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות')),
                ('dispensed_map', models.JSONField(default=dict, verbose_name='מנות שנופקו')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
