# Generated by Django 5.2.5 on 2025-08-19 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_dispenselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenselog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dispenselog',
            name='dispensed_map',
            field=models.JSONField(default=dict, verbose_name='Dispensed map'),
        ),
        migrations.AlterField(
            model_name='dispenselog',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dispenselog',
            name='requested_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Requested type'),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood type'),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='donation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Donation date'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'National ID must be exactly 9 digits.')], verbose_name='National ID'),
        ),
    ]
