# Generated by Django 5.2.5 on 2025-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_dispenselog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationunit',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Donation time'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(max_length=9, verbose_name='National ID'),
        ),
    ]
