# Generated by Django 5.2.5 on 2025-08-19 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_alter_donationunit_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispenselog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='donationunit',
            options={'ordering': ['-donation_date']},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='donationunit',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dispensed at'),
        ),
        migrations.AddField(
            model_name='donationunit',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry at'),
        ),
        migrations.AddField(
            model_name='donationunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('dispensed', 'Dispensed')], default='available', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(db_index=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'National ID must be exactly 9 digits.')], verbose_name='National ID'),
        ),
        migrations.AddIndex(
            model_name='donationunit',
            index=models.Index(fields=['blood_type', 'status'], name='blood_donat_blood_t_a1c643_idx'),
        ),
        migrations.AddIndex(
            model_name='donationunit',
            index=models.Index(fields=['expiry_at'], name='blood_donat_expiry__4e1106_idx'),
        ),
    ]
