# Generated by Django 5.2.5 on 2025-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_dispenselog_options_alter_donationunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=120)),
                ('hospital_city', models.CharField(max_length=120)),
                ('urgency', models.CharField(choices=[('REGULAR', 'Regular'), ('URGENT', 'Urgent')], default='REGULAR', max_length=10)),
                ('requested_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved & Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('plan', models.JSONField(default=dict, help_text='Compatibility plan at submission')),
                ('shortfall', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dispenselog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donationunit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='donationunit',
            name='blood_donat_blood_t_a1c643_idx',
        ),
        migrations.RemoveIndex(
            model_name='donationunit',
            name='blood_donat_expiry__4e1106_idx',
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPENSED', 'Dispensed')], default='AVAILABLE', max_length=16),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(max_length=9, verbose_name='National ID'),
        ),
    ]
