# Generated by Django 5.2.5 on 2025-09-02 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_dispenserequest_alter_dispenselog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserequest',
            name='hospital_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='shortfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='urgency',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('URGENT', 'Urgent')], default='REGULAR', max_length=8),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dispensed at'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DONOR', 'Donor'), ('REQUESTER', 'Requester')], max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
