# Generated by Django 5.2.5 on 2025-09-08 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_profile_default_blood_type_profile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='dispenserequest',
            name='decided_at',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='urgency',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('URGENT', 'Urgent')], default='REGULAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPENSED', 'Dispensed')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(max_length=9, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_blood_type',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('REQUESTER', 'Requester')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'DONOR')), fields=('national_id',), name='uniq_profile_national_id_for_donors'),
        ),
    ]
