# Generated by Django 5.2.5 on 2025-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_donor_birth_date_profile_birth_date_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dispenselog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dispenserequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='donationunit',
            options={'ordering': ['-donation_date']},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='uniq_profile_national_id_for_donors',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Role at time'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Session key'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='hospital_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hospital city'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='hospital_name',
            field=models.CharField(max_length=120, verbose_name='Hospital name'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='plan',
            field=models.JSONField(blank=True, default=dict, verbose_name='Compatibility plan'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='requested_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Requested type'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='shortfall',
            field=models.PositiveIntegerField(default=0, verbose_name='Shortfall'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dispenserequest',
            name='urgency',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('URGENT', 'Urgent')], default='REGULAR', max_length=10, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dispensed at'),
        ),
        migrations.AlterField(
            model_name='donationunit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPENSED', 'Dispensed')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(db_index=True, max_length=9, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Default blood type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('REQUESTER', 'Requester')], max_length=12, verbose_name='Role'),
        ),
    ]
