# Generated by Django 5.2.5 on 2025-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_alter_auditevent_options_alter_dispenselog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile photo'),
        ),
    ]
